config/routes.rb
Rails.application.routes.draw do
  root 'portfolio#index'
  get 'portfolio/work'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-light">
  <div class = "container-responsive">
    <button class = "navbar-toggler hidden-sm-up" type= "button" data-toggle = "collapse" data-target = "#mainNavbar">
      &#9776
    </button>
    <div class="collapse navbar-toggleable-xs" id="mainNavbar">
      <%= link_to "MaxDev", root_path, class: "navbar-brand" %>
      <ul class="nav navbar-nav pull-right">
	<li class = "nav-item"><%= link_to "Work", portfolio_work_path, class: "btn btn-secondary" %></li>
      </ul>
    </div>
  </div>
  </nav>

  <%= yield %>

</body>
</html>

app/views/portfolio/index.html.erb
<div class = 'box-1 col-xs-12 text-center'>
  <div class = 'container'>
    <h5 class = 'text-left'>- Hi</h5>
    <h1>
      My name is <span class = "accented-text">Tyler Pendleton</span> and I am a passionate <span class = "accented-text">Full Stack Web Developer</span> who takes projects from concept to production. I am a <span class = "accented-text">design</span> and <span class= "accented-text">functionality</span> lover.
    </h1>
  </div>
</div>
<div class = 'box-2 col-xs-12 text-center'>
  <div class = 'container'>
    <h1>
      I'm based in <span class = "accented-text-light">New York</span> and am currently working <span class = "accented-text-light">freelance</span>.
    </h1>
    <div class = 'text-left col-xs-8' id = "links">
    <h6>
      <small>- Find me</small>
      <br/>
      <%= link_to "LinkedIn", "https://www.linkedin.com/in/tylerpendleton", class: "btn btn-sm btn-secondary-outline" %> - <%= link_to "GitHub", "https://www.github.com/tylerpendleton", class: "btn btn-sm btn-secondary-outline" %>
    </h6>
  </div>
  <div class = "text-right col-xs-4" id = "links">
    <h6>
      <small> </small>
      <br/>
    <%= link_to "Contact Me", "#", class: "btn btn-sm btn-secondary-outline" %>
  </h6>
  </div>
  </div>
</div>

app/views/portfolio/work.html.erb
<h1>Work Page</h1>